### ISSUE TITLE
Exception when loading a Z calibration in localize

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#11]
After loading a movie (.raw file) in the localize module, setting the parameters, and clicking on the "Load calibration" button I get this error:

Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Processing\python\picasso\picasso\gui\localize.py", line 1372, in excepthook
    errorbox.exec_()
AttributeError: 'StandardButton' object has no attribute 'exec_'

Original exception was:
Traceback (most recent call last):
  File "C:\Processing\python\picasso\picasso\gui\localize.py", line 503, in load_z_calib
    if self.movie_path != []:
AttributeError: 'ParametersDialog' object has no attribute 'movie_path'

**Comment by straussmaximilian** [comment]
Fixed with Commit #957. Was a bug that was introduced from recent changes in the directory settings. Will make changes from now on in the dev branch and make more tests.
