### ISSUE TITLE
3D dialogs

### ISSUE THREAD

**Issue by geokir7** [jungmannlab/picasso#110]
* Picasso version: 0.3.0
* Python version: 3.7
* Operating System: MAC OS Catalina

There's no undrift from picked (3D) and slice (3D) dialogs.

**Comment by straussmaximilian** [comment]
Hi, are you using data with 3D information?
Picasso checks for z coordinates and will not display the dialogs if the data contains now 3D information. If the data contains 3D information, do you mind sharing the dataset so I can investigate it?
