### ISSUE TITLE
An issue and solution to run the PowerShell script "createShortcuts.ps1"

### ISSUE THREAD

**Issue by sasakihrs** [jungmannlab/picasso#13]
This is just for the reference when other users hit the same issue.

We run Picasso on Windows Server 2008 R2 Enterprise SP1 and recently found that "createShortcuts.ps1" didn't run at the last step of installation (didn't create any shortcuts). It was due to Powershell version difference. In our machine, Ver. 2 of PowerShell is installed instead of Ver. 3. I added one line as below to the top of the script and it finally created the shortcuts:
if(!$PSScriptRoot){ $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent }

**Comment by straussmaximilian** [comment]
Thanks for sharing!
