### ISSUE TITLE
Opening raw file in the localize module.

### ISSUE THREAD

**Issue by ajasja** [jungmannlab/picasso#154]
* Picasso version: dde20a9
* Python version: 3.8
* Operating System: Linux 64 bit

### Description

I'm trying to open a raw file in the localize module, but raw files are not shown in the open dialog.
![image](https://user-images.githubusercontent.com/19926/99479224-9f107600-290a-11eb-993a-6ea74d625084.png)

### What I Did

```
python -m picasso localize
File->Open Movie
```

**Comment by ajasja** [comment]
Fix in https://github.com/jungmannlab/picasso/pull/155

Also workaround is to drag & drop files.

**Comment by straussmaximilian** [comment]
Thanks for reporting the issue and also coming up with a fix. This is very much appreciated!

**Comment by ajasja** [comment]
You are very welcome! It was luckily an easy fix:)
