### ISSUE TITLE
wishlist: reindex frames for the join module

### ISSUE THREAD

**Issue by ajasja** [jungmannlab/picasso#156]
* Picasso version: dde20a9
* Python version: 3.8
* Operating System: Linux 64 bit

### Description

Using `python -m picasso join file1 file2` produces localization files that can't be used for drift correction.
I propose and option (for example `-reindex_frames` ) that would make sure that frames from file two continue sequentially.  
Such a localization file could then be used for drift correction. 

### XYZ problem?
I have 50k frames delta vision file that I can't convert to a single raw file. I was planning to fit smaller parts of the file and then somehow join the localizations.

**Comment by straussmaximilian** [comment]
Excellent idea! I just implemented this #8181c19
The new default is to reindex, adding the flag "-k" after the files keeps the frame index.

**Comment by ajasja** [comment]
Thanks!
