### ISSUE TITLE
Localize "cannot set parent" error when using GPU fit

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#159]
* Picasso version: 0.3.1
* Python version: 3.8
* Operating System: Win 10

Trying to 2d localize a raw file I loaded into localize, launched via Anaconda. Spot finding appears to occur (boxes turn yellow from preview) but then localize freezes and "An error occurred" box pops up and the system hangs. In the Anaconda command line, I get the error screenshot below. This is with GPUfit on. Notably, CPUfit worked ok. I just updated Picasso by git pull and directions on the main page. I have pyGpufit 1.1.0 installed and the test works correctly, running CUDA 11. I've used gpu fit successfully on other computers in the lab so this seems to be recent behavior from Picasso. This happened on another lab computer where I recently (in the last week) updated Picasso as well.

<img width="619" alt="Screen Shot 2020-11-23 at 5 29 44 PM" src="https://user-images.githubusercontent.com/48363706/100024492-e4beba00-2db4-11eb-81d1-4a5936ad4e7e.png">

**Comment by LREIN663** [comment]
I am having the same problem also on Win 10, Picasso 0.3.1 and Python 3.8, but I found a workaround: 
The error doesn't occur when I am localizing via the prompt (see Picasso documentation -> cmd -> localize).
_python -m picasso localize test.tif -a "lq-gpu"_
Maybe this could be a short term solution for you .
