### ISSUE TITLE
Setup default EM gain (in Localize) and camera pixel size (in Render)

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#16]
I set up the config.yaml file for our camera according to the Wiki. However, there are two settings that I can't set by default:
- The EM gain in the Localize module (to 100 instead of 1)
- The pixel size in the Render module (to 160 nm instead of 130)
Is there a way to do this via the config.yaml file?

Also is there a way to set the default processing parameters of the Localize module (box size, gradient etc.) via the config.yaml file?

**Comment by straussmaximilian** [comment]
I made some commits that should address this issue:

- Use 'DefaultGain' in the config.yaml to set the EM gain 

- Use 'Pixelsize' to define a pixel size for the camera. It will be displayed in localize and will be saved in the yaml file for the hdf5 after reconstruction and will be subsequently recognized by render

The processing parameters box size and gradient will now be remembered and loaded when re-opening localize.
