### ISSUE TITLE
Can't get shortcuts to work

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#17]
I've generated the module shortcuts using the Powershell script. However nothing happens when I double click them. I added Anaconda and Anaconda/Scripts to my PATH environment variable. 

This may be related: I can use picasso from the Anaconda Prompt, but not from the Windows 10 default command line terminal. After adding Anaconda to my PATH variable, when I launch the command line, I can do "conda list" but if I do "conda activate picasso" (the environment where I installed picasso) I get the following error:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". C:\Users\NeuroCyto\Anaconda3/etc/profile.d/conda.sh" >> ~/.bashrc

or, for all users, enable conda with

    $ sudo ln -s C:\Users\NeuroCyto\Anaconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bashrc

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bashrc file.  You should manually remove the line that looks like

    export PATH="C:\Users\NeuroCyto\Anaconda3/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bashrc file! ^^^
```

**Comment by straussmaximilian** [comment]
To me the error message looks like that there is still something wrong with the PATH / the correct activation. If you use Anaconda, what you can try is to run `C:\ProgramData\Anaconda3\Scripts\activate.bat`. If this doesn't help I would recommend re-installing Anaconda. During installation you will be prompted to add Anaconda to the PATH variables.
