### ISSUE TITLE
crash when opening picked localizations in Render

### ISSUE THREAD

**Issue by pnickels** [jungmannlab/picasso#192]
* Picasso version: 0.3.1
* Python version: 3.8
* Operating System: Win10, MacOS 11.2.3, Ubuntu 18.04 LTS

### Description
When I try to open picked localizations in the Render module, I consistently get the attached "IndexError: list index out of range" message. I initially thought it was a problem with the Picasso installation on our Linux server, but I get the same error on Windows and Mac systems.

![210406_picasso_crash](https://user-images.githubusercontent.com/37538080/113836412-27de6000-978d-11eb-8324-217b0c3b2d6b.PNG)

**Comment by straussmaximilian** [comment]
Should be fixed now. Looked like the bug only appeared when using the File menu and not the drag and drop.

**Comment by pnickels** [comment]
Thanks Maximilian!
