### ISSUE TITLE
GPUfit option not available using picassosr Python package

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#222]
* Picasso version: picassosr 0.3.7
* Python version: 3.8
* Operating System: Win 10

When I install picasso from github and launch programs from the picasso folder using `python -m picasso localize` for example, the "Use GPUfit" option is available and works. However when I install picasso as the picassosr python package with pip, the "Use GPUfit" option is greyed out and unavailable.

pygpufit is installed in the environment
![Screen Shot 2021-11-02 at 5 42 50 PM](https://user-images.githubusercontent.com/48363706/139956017-4dedf125-5612-4014-aa96-dceb6f0b0ae4.png)

but GPUfit is unavailable
![Screen Shot 2021-11-02 at 5 42 12 PM](https://user-images.githubusercontent.com/48363706/139956029-59d590d7-da78-497b-8394-dfb819233953.png)

I installed pygpufit in this environment the same way I've installed it in the past for github installations. Am I missing a step somewhere to make it available? 

Thanks

**Comment by straussmaximilian** [comment]
Should be fixed now. Currently pushing the new version to [PyPi](https://github.com/jungmannlab/picasso/actions/runs/1421985303) - do you mind to test if this solves the problem?

**Comment by GolgiWhillikers** [comment]
I ran `pip install picassosr --upgrade`, upgraded fine to 0.3.8. GPUfit box is no longer greyed out.

However I ran into an error when it tried to do the GPU fit on my test region. The first time, python just hung. The second time, I got the following error message:

<img width="423" alt="Screen Shot 2021-11-04 at 12 11 14 PM" src="https://user-images.githubusercontent.com/48363706/140376678-c68954b6-6979-4a5c-8fc5-a408350c24b6.png">

And in the anaconda prompt:

<img width="871" alt="Screen Shot 2021-11-04 at 12 12 09 PM" src="https://user-images.githubusercontent.com/48363706/140376789-23cc7e70-e688-4c06-9770-361226690b0c.png">

**Comment by GolgiWhillikers** [comment]
I'm actually getting the same error using python installed via github (ie launching with `python -m picasso localize`) and using an older version of picasso (0.3.1), on a totally different computer. I updated to 0.3.8 via git pull and saw the same behavior. In this case, I'm using pyGpufit 1.1.0 due to having an older GPU. Same problem with 0.3.8 installed in this way.

**Comment by straussmaximilian** [comment]
Hi,
it looks like that `time.clock` is depreciated in [Python 3.8](https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8). Do you mind trying downgrading your Python environment? As this is a pygpufit-issue I will create an issue there.

**Comment by straussmaximilian** [comment]
Hi, so I just checked.
The current version in gpufit should not have this issue and was closed already some time [ago].(https://github.com/jungmannlab/picasso/issues/139)

Do you mind trying the latest gpufit version and install?

**Comment by GolgiWhillikers** [comment]
Oh OK thanks - I uninstalled pygpufit 1.10 and installed pygpufit 1.2.0 in both my picassosr and git pulled environments (both picasso 0.3.8 I believe), and GPU fit worked correctly in each. Thanks.

**Comment by straussmaximilian** [comment]
Awesome!
