### ISSUE TITLE
3D reconstruction parameters log

### ISSUE THREAD

**Issue by aaristov** [jungmannlab/picasso#23]
I found lots of parameters in the yaml file after localizing astigmatism, but one important is missing: Which calibration has been used. I would like to have it in the yaml file along with the camera gain-baseline settings.
Thanks.
![image](https://user-images.githubusercontent.com/11408456/44202390-224f2a00-a14c-11e8-9e1b-885752f78dbf.png)

**Comment by straussmaximilian** [comment]
I understand, that would be useful. Would you rather have the file path of the configuration file that has been used or the fit coefficients?

**Comment by aaristov** [comment]
Exactly. Would be great also to load automatically calibration file after saving it.

**Comment by cleterrier** [comment]
So I'd say both: file path and fit coefficients

**Comment by straussmaximilian** [comment]
Commit #1023 in the dev branch. 
![screen shot 2018-08-20 at 7 00 26 pm](https://user-images.githubusercontent.com/16521288/44355016-aa666400-a4ab-11e8-9e6e-b174087436e3.png)

**Comment by aaristov** [comment]
Fantastic! Thanks a lot.
