### ISSUE TITLE
A few issues in Localize GUI in picassosr 0.4.1 - automatic drift correct; error with database save; GPUfit box greyed out

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#245]
* Picasso version: picassosr 0.4.1
* Python version: 3.8.12
* Operating System: Win10

Three issues I've run into with recent the current Picasso update:

1) Running localize from the GUI is automatically performing drift correction now. I'm not sure which version it changed in but I have not noticed it before. However I don't see any way to turn this off or on or to change the segmentation value in the GUI, as you can in the cmd line version of localize. This would be important as I don't always want to drift correct with 1000 frames or to drift correct at all (example beads for dual-view calibration, which actually generate another error because there are <1000 frames). For now I can just overwrite any drift correct I don't want, but it would be helpful to add these settings to the parameters pane if the GUI is now going to automatically drift correct. My suspicion is this has to do with the new sever/add to database settings trying to automatically drift correct, but turning off Add to database did not stop drift correction (and parameters can't be changed).

2) On launching the Localize module from CMD the new "Add to database" option is checked but I think is yielding an error when localization is done. See the attached screenshot. The actual localizations hdf5 file is saving fine, but this error pops up every time I localize something from the GUI whether Add to database is checked or not. I attached the full traceback as well.

3) On launching Localize, the "Use GPUfit" checkbox is greyed out and unselectable (LQ Gaussian is the default fit method), and if I do localize, GPUfit is not active. If I select a different fit method and then reselect LQ, the GPUfit option is now selectable, and if I localize, GPUfit works.

I've been using the cmd line localize lately so I'm also not sure if any behavior is changed on that end with the recent updates. I haven't noticed errors or issues saving/using GPUfit.

Thanks

```
<img width="1329" alt="Screen Shot 2022-06-07 at 10 18 01 AM" src="https://user-images.githubusercontent.com/48363706/172403546-c46d99ed-951e-463c-ba01-697cff3ac631.png">

<img width="503" alt="Screen Shot 2022-06-07 at 10 09 49 AM" src="https://user-images.githubusercontent.com/48363706/172402608-33af323b-c480-4c87-b735-ed0d640bc0a3.png">

<img width="768" alt="Screen Shot 2022-06-07 at 10 15 58 AM" src="https://user-images.githubusercontent.com/48363706/172403077-652410e8-378a-4145-897d-0773f1c55f9f.png">

**Comment by straussmaximilian** [comment]
Hi,
there will be a revision of the [Picasso Server version](https://github.com/jungmannlab/picasso/projects/6#card-83092319), where I can adress these issues.

1) Would you rather be able to specify the segmentation or simply not perform drift correction after localization?
2) & 3) Thanks fro reporting, this looks like a bug.
