### ISSUE TITLE
File loading error in Render 0.2.0

### ISSUE THREAD

**Issue by hiroshisasak1** [jungmannlab/picasso#25]
I've just updated Picasso and noticed that Render throws an error when it tries to open the data saved with Render.

1. Open Render
2. Load data which is processed with the previous version of Localize (0.1.0)
3. Save localizations as a new hdf5 file
4. Close Render
5. Load data saved at step 3
6. Get the following error
![screen shot 2018-10-12 at 14 09 17](https://user-images.githubusercontent.com/23729528/46886324-934b4f00-ce28-11e8-8bf1-b0e05b339f9e.png)
7. Close the error message
8. Load the same data at step 2
9. Get the different error
![screen shot 2018-10-12 at 14 18 13](https://user-images.githubusercontent.com/23729528/46886881-22a53200-ce2a-11e8-89bd-645eebf94722.png)

**Comment by straussmaximilian** [comment]
Hi, thanks for letting me now. Should be fixed with 0.2.1.
