### ISSUE TITLE
File loading error in Localize module

### ISSUE THREAD

**Issue by chaosunlucas** [jungmannlab/picasso#26]
I installed Picasso using Anaconda on Mac. When I try to load .tiff files to Localize, it reports error as follows:

![screen shot 2018-10-19 at 16 51 24](https://user-images.githubusercontent.com/44297977/47226832-c8741600-d3c1-11e8-9879-c7219f6c4dc7.png)

**Comment by straussmaximilian** [comment]
Hi, are you using MicroManager for your TIFFs? Do you mind uploading it for me so that I could troubleshoot what is causing this error?
In the meantime you could try saving it as a *.raw file.

**Comment by chaosunlucas** [comment]
Yes, we used micromanager to obtained the TIFFs. It only reports this error when I try to upload a list of TIFFs. It works fine when I only have one TIFF file in the folder. The TIFFs are about 20 GB. Are they too big to upload?

**Comment by chaosunlucas** [comment]
> Hi,
> Thanks for sharing the screenshot. Which MicroManager version are you using? I guess one ome.tif file (even the one with 644mb) would be enough for uploading.


Version 1.4.20

Github does not allow uploading files bigger than 10 MB

**Comment by chaosunlucas** [comment]
When I change all file names to *.raw and load to Localize, it asks for:
![screen shot 2018-10-19 at 17 32 29](https://user-images.githubusercontent.com/44297977/47228258-11799980-d3c5-11e8-8651-cf33313350de.png)


Should I change these values?

**Comment by straussmaximilian** [comment]
Hi, I guess there is a problem with the MicroManager-MetaData here. At some point, I need to implement the different versions (1.4.22 / 1.4.20 / 2.0). Anyhow, could you try fetching the latest commit and see if it works? I wrote a little hotfix. 
As for the raw data: You need to convert it via, i.e. ImageJ and then manually enter the movie info in the dialog.

**Comment by chaosunlucas** [comment]
> Hi, I guess there is a problem with the MicroManager-MetaData here. At some point, I need to implement the different versions (1.4.22 / 1.4.20 / 2.0). Anyhow, could you try fetching the latest commit and see if it works? I wrote a little hotfix.
> As for the raw data: You need to convert it via, i.e. ImageJ and then manually enter the movie info in the dialog.

Sorry I'm a newbie with Github... What exactly should I do to fetch the latest commit? Thanks

**Comment by straussmaximilian** [comment]
Navigate to your picasso folder with terminal and then type `git pull`. It then fiches the latest update.
![screen shot 2018-10-19 at 5 50 57 pm](https://user-images.githubusercontent.com/16521288/47229237-89e15a00-d3c7-11e8-8804-b2d0d12964fb.png)

**Comment by chaosunlucas** [comment]
> Navigate to your picasso folder with terminal and then type `git pull`. It then fiches the latest update.
> ![screen shot 2018-10-19 at 5 50 57 pm](https://user-images.githubusercontent.com/16521288/47229237-89e15a00-d3c7-11e8-8804-b2d0d12964fb.png)

It worked! Thanks a million!

**Comment by straussmaximilian** [comment]
Great. There are some known bugs when working with MacOsX. See also: https://github.com/jungmannlab/picasso/issues/19. Let me know if you stumble across something.
