### ISSUE TITLE
RCC drift correction failed

### ISSUE THREAD

**Issue by chaosunlucas** [jungmannlab/picasso#27]
Our picasso is installed via python (Anaconda) on Mac. I did not have this RCC failure problem for previous rendering. But one particular set of data reports RCC failure no matter how I change the segmentation. The number of locs is comparable to the data I rendered before.
![screen shot 2018-10-25 at 10 28 39](https://user-images.githubusercontent.com/44297977/47486483-c4704a00-d840-11e8-96e8-d79070193faf.png)

**Comment by straussmaximilian** [comment]
Hi, The RCC can fail if there is too much drift present. You can always try to do undrift by picked first and then try the RCC again.
If you mind sharing the dataset, I can investigate to see what's causing the problem (i.e., upload on owncloud).
