### ISSUE TITLE
QObject::setParent: Cannot set parent, new parent is in a different thread

### ISSUE THREAD

**Issue by IrrelevantNameTom** [jungmannlab/picasso#270]
* Picasso version: 0.4.11
* Python version: 3.10.6 and 3.8.13
* Operating System: windows10

Hi,
Whether I use the standalone or install through pip the picasso localize freezes when launching Identify or Localize.
A windows "An error occured" pops up but without any error message. Poweshell precises "QObject::setParent: Cannot set parent, new parent is in a different thread"

I am reading a 16bit tif file (on computer not server). I tried different sizes (10, 100 and 1000 frames)

I also have an warning when launching localize:
"picasso\__init__.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  CONFIG = _yaml.load(config_file)"

But I dont think its related.
Thanks : )
Tom

**Comment by straussmaximilian** [comment]
Hi,

This sounds like a bug.
The yaml warning is unrelated.
Could you share the file that caused you problems to investigate?

**Comment by IrrelevantNameTom** [comment]
Hi,

Thank you for your answer. Here is the file we try to read. 
[Measurement1bin10.zip](https://github.com/jungmannlab/picasso/files/9912627/Measurement1bin10.zip)

This is a .tif file, 16bit. I did not find test file in the package, do you find you could share a valid one so I can exclude it comes form my format ?

Thank you : )
Tom

**Comment by rafalkowalewski1** [comment]
Hey Tom,

I successfully opened and localized your file and I cannot reproduce your issue unfortunately. Can you please try identifying/localizing with this dataset?
[test.ome.tif.zip](https://github.com/jungmannlab/picasso/files/9918747/test.ome.tif.zip)

Bests,
Rafal

**Comment by IrrelevantNameTom** [comment]
Hi Rafal,

Thanks for the test data. The same error happened unfortunately. Here is a screenshot of the error. I will try to install it on another computer and let you know if this is working better. 


Tom
![20221102_an_error_occured](https://user-images.githubusercontent.com/64032595/199474634-557b2988-d777-40d2-b97b-8c966a0491cd.png)

**Comment by IrrelevantNameTom** [comment]
Update: I installed the standalone Picasso on another computer and everything worked ok. The bug probably comes from my current computer. I will tell you if I can solve this.

Tom

**Comment by rafalkowalewski1** [comment]
Hey Tom, thanks for the updates!
