### ISSUE TITLE
Picasso localize crashes when using simulated raw files

### ISSUE THREAD

**Issue by mb1069** [jungmannlab/picasso#275]
* Picasso version: unknown
* Python version: 3.8.10
* Operating System: Ubuntu

### Description
I simulated a dataset using a 3d PSF, and the simulated yaml file contains an unreadable entry which causes command  `picasso localize` to crash

### What I Did

```
picasso localize -b 31 simulated_file.raw

Error message:
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:numpy.core.multiarray._reconstruct'

```

**Comment by rafalkowalewski1** [comment]
Hey Miguel,

Can you please send me the .yaml file?

**Comment by mb1069** [comment]
> Hey Miguel,
> 
> Can you please send me the .yaml file?

Hi, here's a gist of the file as produced by picasso's simulation module
https://gist.github.com/mb1069/ca68e98849af5df5529cb88ba321d3d1

**Comment by rafalkowalewski1** [comment]
Hey Miguel,

Thank you for the data. This is an error we have spotted recently too and it will be solved in the next release this/next week

Bests,
Rafal
