### ISSUE TITLE
Documentation for average3 module

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#288]
* Picasso version: 0.3.8
* Python version: 3.8
* Operating System: win 10

We are interested in using the Average3 module for averaging some 3d structures we have imaged. However we can’t find any documentation for its use, and it seems quite different from the standard Average module, which does have documentation. Is there a source for documentation I’m missing, or can it be added here? Thanks

**Comment by rafalkowalewski1** [comment]
Hello,

I will try to make a documentation for this module in the near future, thank you for pointing this out!

Bests,
Rafal
