### ISSUE TITLE
Choosing a "Custom" colormap in the Render module can't be cancelled and makes the module unusable

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#298]
* Picasso version: 0.5.4
* Python version: 3.8
* Operating System: Windows 10

While trying out stuff in the Render module, I chose a "Custom" colormap in the dropdown menu. It displayed a file chooser dialog, asking for .npy file. I don't have any colormap .npy file to feed it, so I clicked "Cancel". This resulted in errors of the Render module at the next action, complaining about the custom colormap not being a defined object. Now when I relaunch the module, it stubbornedly starts with the colormap file chooser dialog, and refuses to work without a valid colormap .npy file from my computer (and as explained, I have none and could not find one on the net).

How to get out of this trap?

**Comment by rafalkowalewski1** [comment]
Hi Chrstophe,

Firstly, sorry about this error, I will try to fix it in the next release (hopefully this week) and thank you for pointing out this bug.

The solution is to drag and drop a localization file (.hdf5) of your choice onto the render window. You will receive the error again, however, you can now open the display settings dialog by clicking Ctrl+D. There, you can go back to the colormap you like the most.

Again, thank you for your valuable feedback and I hope this helps.

Bests,
Rafal
