### ISSUE TITLE
Export as PDF for Picasso Design

### ISSUE THREAD

**Issue by oodegard** [jungmannlab/picasso#3]
It would be great if you could add a possibility to save as eg. .pdf from Picasso: Design. This way the artwork can be modified in programs such as adobe illustrator.

**Comment by straussmaximilian** [comment]
I agree. Saving in a vector format makes sense to generate data for generating nice graphics. I'll look into it.

**Comment by straussmaximilian** [comment]
Implemented with commit 917. Screenshot now has the option to choose between *.png and *.pdf.
