### ISSUE TITLE
Render Clustering DBSCAN - missing information in output files

### ISSUE THREAD

**Issue by TanjaOtt** [jungmannlab/picasso#306]
* Picasso version: v0.5.6
* Python version: 3.9.7
* Operating System: Windows 11

### Description

I am missing the information on mean_frame and std_frame in the output files of DBSCAN (Render). The problem, which I have, was mentioned in a previous issue (Render Clustering files output no more '_dbscluster' information). This issue was closed and in the newest version (v0.5.6) it is stated in the description that cluster center files would contain analogous columns to the ones generated before the 0.5.x releases. I could find the columns area, convex_hull and n in the cluster center file, but the columns mean_frame, std_frame, std_x and std_y, which could be found in the previously created "_dbclusters.hdf5" file, were still missing. Espacially the columns mean_frame and std_frame are important for us to filter our data. It would be really nice if these columns could still be integrated!

### What I Did

I used the one-click installer for Windows and opend Render. I loaded my linked localizations into Render and clicked on Postprocess - Clustering - DBSCAN, entered my parameters and checked the box "Save cluster centers" and looked into the "_clustered_cluster_cender.hdf5" file.

**Comment by rafalkowalewski1** [comment]
Hey Tanja,

Sorry for the late reply and inconvience. 

Mean frame can be found in the "frame" column - the reason why the naming is not so clear is to allow cluster centers to be displayed in Render (the frame column is required for display)
Std frame should be included (in Filter, right after "frame", under "std_frame"). Are you sure this columns is missing? There may be a bug in some particular case.
When it comes to std_x and std_y, I missed them in saving, my apologies. I will improve that in the future release.
