### ISSUE TITLE
Cannot open .tiff files on M1 Mac

### ISSUE THREAD

**Issue by aaliyari** [jungmannlab/picasso#307]
* Picasso version: v0.5.6
* Python version: 3.8.16
* Operating System: MacOS Monterey 12.5 (M1 pro)

### Description
I followed the installation instructions for the latest version of Picasso on my M1 Mac, and I get the following error when I load a tiff file into Picasso. Any help is appreciated.

<img width="420" alt="Screen Shot 2023-01-20 at 17 02 59" src="https://user-images.githubusercontent.com/22183094/213813665-e3d0724f-65be-4cf4-81be-cf4996069153.png">

**Comment by rafalkowalewski1** [comment]
Hey Ali,
Most probably, this is because you're using a .tiff file. Picasso Localize expects one of the two formats: .ome.tif and NDStackTIff. What you can do, is changing the name of your file(s) to end with ".ome.tif" instead of ".tiff".

Let me know if that helps.
Bests,
Rafal
