### ISSUE TITLE
First frame is numbered "0" in Filter

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#31]
Not sure if this is intended, but in the Filter module, the first frame is numbered 0. I'd expect it to be 1?

**Comment by straussmaximilian** [comment]
Hi,
Arguably the first frame should have number 1.  However, as Python uses zero-based indexing the first frame has number 0 to make the code more consistent. I.e., when considering a drift file: drift[0] is the first element of the drift-array.
