### ISSUE TITLE
Wishlist: make pixelsize a positional argument in cmd line dbscan

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#315]
* Picasso version: 0.5.7
* Python version: 3.8
* Operating System: Win 10

I was having an issue with cmd line dbscan in picasso 0.5.6, as it was not actually asking me for pixelsize:
![Screen Shot 2023-02-08 at 3 49 05 PM](https://user-images.githubusercontent.com/48363706/217647749-93f150d9-e774-49c3-9d24-cfce108a39bc.png)

On update to 0.5.7 the problem was resolved and the pixelsize request did occur correctly, and the data were clustered. However to me it would be more useful to have the pixelsize input be in the cmd line call (ie `picasso dbscan files radius density psize`). This makes it more fully callable from another coding environment (for example we call cmd functions from matlab since that's where the rest of our processing is; I recognize one could call clusterer.py functions directly from clusterer.py in python environments). I can edit on my individual instance, but would this be the better long term solution? I see there are a lot of changes going on with the clustering algorithms, and I'm also happy to take other solutions.

Thanks

**Comment by rafalkowalewski1** [comment]
Hi,

Thank you for your input, we will likely add this in the next release!

Bests,
Rafal
