### ISSUE TITLE
Wishlist: add set ROI parameters to cmd line Localize and GUI

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#316]
* Picasso version: 0.5.7 and earlier
* Python version: 3.8
* Operating System: Win 10

In the Localize GUI, it is possible to hand draw ROIs and localize within them. However, in many cases one would want to set the specific bounds of an ROI to localize within. For example, with a multicolor/dual view setup, one may want to localize only from x<256, and then separately from pixel>256, rather than trying to draw those boxes. It would be useful both in the Localize GUI to have this option (similar to the recent addition of specific cutoffs in Filter) as well as in the cmd line `picasso localize` call. I had implemented a version of this with my own copy of __main__ to add an -roi argument that takes a "minx,miny,maxx,maxy" argument (ie `picasso localize ... -roi 0,0,256,300` would localize the left half of a 512x300 px image). I'm happy to share this, but there might be a cleaner fix (I'm not a python or github pro, so I'm not confident I could appropriately fork and pull request this).

Thanks

**Comment by rafalkowalewski1** [comment]
Hi,

Thank you for your valubale suggestions, we will be happy to add them to in one of the next releases. It would be great to see how you implement them, it will certainly be much easier to incorporate them with your help : ) 

Bests,
Rafal
