### ISSUE TITLE
Wishlist: Filtering out adjacent localization

### ISSUE THREAD

**Issue by IrrelevantNameTom** [jungmannlab/picasso#341]
* Picasso version: 6.0
* Operating System: win10

Hello,

I am trying to image densely packed molecules and in order to avoid the appearance of adjacent blinking and hence biased localization, I have to dilute the imager probe concentration drastically (20-50 pM max), which also greatly increase the total time required to accumulate enough localization events to build a picture. It would be very convenient for me if I could increase the imager concentration and simply filter out these events during the analysis. I believe this issue has been nicely described in 
https://doi.org/10.1016/j.bpj.2018.06.024 . 

Do you think such a procedure might be implemented in the future ?

Thanks !
Tom

**Comment by rafalkowalewski1** [comment]
Hey Tom,

Thank you for giving the suggestions. We plan to add some novelties to Picasso Localize and I think this may be a good idea too. We will consider adding it, however, this is not likely to happen in the nearest future.

Bests,
Rafal
