### ISSUE TITLE
Errors with numpy version, then lack of PyQt5 when installing from source on Windows

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#342]
* Picasso version: 0.6.1 (from source)
* Python version: 3.8
* Operating System: Windows 10

I followed the instructions to install Picasso from source in order to use GPUfit under Windows 10, from 1 to 7:

For Developers
^^^^^^^^^^^^^^

If you wish to use your local version of Picasso with your own modifications:

1. Open the console/terminal and create a new conda environment: ``conda create --name picasso python=3.8``
2. Activate the environment: ``conda activate picasso``.
3. Change to the directory of choice using ``cd``.
4. Clone this GitHub repository by running ``git clone https://github.com/jungmannlab/picasso``. Alternatively, `download <https://github.com/jungmannlab/picasso/archive/master.zip>`__ the zip file and unzip it.
5. Open the Picasso directory: ``cd picasso``.
You can modify Picasso code from here.

*Windows*
'''''''''

6. If you wish to create a *local* Picasso package to use it in other Python scripts (that includes your changes), run ``python setup.py install``. 

I end up with the following error: `error: numpy 1.19.2 is installed but numpy<1.25,>=1.21 is required by {'numba'}`

Now if I try to run a module like `picasso localize`, I get another error about the lack of PyQt5:
```
(picasso) C:\Users\chris\christo\Processing\picasso>picasso localize
Traceback (most recent call last):
  File "\\?\C:\Users\chris\.conda\envs\picasso\Scripts\picasso-script.py", line 33, in <module>
    sys.exit(load_entry_point('picassosr==0.6.1', 'console_scripts', 'picasso')())
  File "C:\Users\chris\.conda\envs\picasso\lib\site-packages\picassosr-0.6.1-py3.8.egg\picasso\__main__.py", line 1658, in main
    from picasso.gui import localize
  File "C:\Users\chris\.conda\envs\picasso\lib\site-packages\picassosr-0.6.1-py3.8.egg\picasso\gui\localize.py", line 15, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5.sip'
```
What did I do wrong? Which steps should I modify?

**Comment by rafalkowalewski1** [comment]
Hi Christophe,

Apologies for the late reply and thank you for your feedback. Unfortunately, we recently encounter many issues with dependencies that we will try to solve with the next update, hopefully by the end of August.
