### ISSUE TITLE
Error while localizing spots with .ims files

### ISSUE THREAD

**Issue by annafasoli** [jungmannlab/picasso#344]
* Picasso version: 0.5 and above
* Python version: N/A - using the installer
* Operating System: Windows 10

### Description

The .ims files are loading fine, and I can start running the localization step but then I get an error when all the locs are found, at the "Preparing Fit" stage.
Sometimes the error is an empty error window, sometimes it shows like below.

Version 0.4.11 works OK.

Thank you,
Anna

![Picasso error](https://github.com/jungmannlab/picasso/assets/88112254/fd7609d2-bc80-44d2-8f8e-4a3ad49f52f6)
![Picasso error_2](https://github.com/jungmannlab/picasso/assets/88112254/fa7aeb72-6d9f-40b6-9597-40191de5d3e8)

**Comment by rafalkowalewski1** [comment]
Hi Anna,

Thank you for your message. Could you please share the file so that I could take a closer look?

Bests,
Rafal

**Comment by rafalkowalewski1** [comment]
you can send it to this email: kowalewski@biochem.mpg.de

**Comment by annafasoli** [comment]
Thanks, Rafal. I have shared the data with you
