### ISSUE TITLE
Query about Liquid Handling Steps(pipetting scheme) in Generated PDF

### ISSUE THREAD

**Issue by imagicd86** [jungmannlab/picasso#372]
Description
I am trying to generate a PDF that outlines the liquid handling steps for a 96-well plate. While the PDF does indicate the well numbers, it does not specify the order in which the samples should be added. I would like to know where this order is generated and how to include it in the PDF.

Picasso Version
0.6.1

Python Version

Operating System
windows11

Steps to Reproduce

Expected Behavior
I expected the PDF to include not just the well numbers but also the sequence in which the samples should be added.

Actual Behavior
The generated PDF only contains the well numbers without any information on the sample addition sequence.

Additional Information
[1112.pdf](https://github.com/jungmannlab/picasso/files/12615370/1112.pdf)

**Comment by rafalkowalewski1** [comment]
Hi,

All the staple strands in the PDF attached need to be mixed together, so no order is required.

It is a good practice though, to mix them step-by-step, for example, first mix row 1, then row 2, etc. This minimizes the effects of pipetting errors.

I hope this answers your question.
Bests,
Rafal
