### ISSUE TITLE
Issue with yaml constructor using Picasso Join

### ISSUE THREAD

**Issue by GolgiWhillikers** [jungmannlab/picasso#392]
* Picasso version: 0.6.4
* Python version: 3.10
* Operating System: Win 10

Edit after posting -  Sorry I can't edit the title to reflect this, but I've found that this problem actually affects all cmd functions after picasso localize. When I localize my nd2 files with picasso 0.6.4, any downstream functions (tested undrift, link, dbscan, and join) hit the same error detailed below, and all of these again were "fixed" with the unsafeLoader change detailed below.

I am running into an issue with yaml constructs when nd2 files are localized in picasso 0.6.4 that did not occur in 0.6.0. Essentially, I localize several files using picasso localize cmd line function, then use picasso join in command line to combine them. This worked fine in 0.6.0. In 0.6.4, I get an error in picasso join in yaml constructors that is a line in the nd2 metadata section of the _locs.yaml file.

Here is a screenshot of the command and associated error
<img width="1770" alt="Screenshot 2023-10-04 at 3 53 22 PM" src="https://github.com/jungmannlab/picasso/assets/48363706/40405aa0-fc08-44c1-be8a-fbd9ec9dd184">

Here is the section of _locs.yaml that threw the error
<img width="1249" alt="Screenshot 2023-10-04 at 3 53 55 PM" src="https://github.com/jungmannlab/picasso/assets/48363706/1fe2c3bb-9aef-4e47-ab7e-3605a52c7720">

This appears to specifically be an issue with picasso 0.6.4, I suspect stemming somewhere in the localize workflow:
-If I localize files in 0.6.0 and join in 0.6.0, this error does _not_ occur
-If I localize in 0.6.4 and join in 0.6.0, this error _does_ occur
-If I localize in 0.6.0 and join in 0.6.4, this error does _not_ occur
-If I localize in 0.6.4 and join in 0.6.4, this error _does_ occur

I I was able to "fix" this in 0.6.4 by editing line 201 (load_info function) of picasso's io.py to use the _yaml.UnsafeLoader instead of _yaml.FullLoader (taken from https://github.com/yaml/pyyaml/issues/482, but honestly I don't really know what I'm doing and just tried something that hit the keywords). However these functions are the same in both picasso io.py 0.6.0 and 0.6.4 so I suspect it's not actually the problem, and just a downstream solve. 

Here is the line of io.py that I changed to unsafeloader to "fix" the problem
<img width="828" alt="Screenshot 2023-10-04 at 3 54 20 PM" src="https://github.com/jungmannlab/picasso/assets/48363706/4d1e87f0-9a87-4687-871a-0f1bab1c8f8d">

I have noticed a warning about nd2 file garbage collection in picasso localize from cmd line in picasso 0.6.4 that I don't get in 0.6.0. It doesn't prevent localization, but does pop up, and could be unrelated. I see there is also a new version of the python nd2 package being used and an nd2reader - I don't know the difference with older verisons but I could see that being the source.

Here is the line in picasso 0.6.0 with no error
<img width="1251" alt="Screenshot 2023-10-04 at 4 18 52 PM" src="https://github.com/jungmannlab/picasso/assets/48363706/b5c3ca0d-d1d0-4ce2-90c2-3274e1d2c366">

And here is the line in picasso 0.6.4 with the error
<img width="1509" alt="Screenshot 2023-10-04 at 4 19 33 PM" src="https://github.com/jungmannlab/picasso/assets/48363706/eafc976e-c43d-4058-ac21-97bc0f5be34d">

I have also noticed that the yaml files after picasso localize are not the same between the two picasso versions, which again makes me think it's something about the change in nd2 reading. See here for the loc and yaml files localized with both versions that I've been using. I don't know if this problem affects loc files from other image file types or not.
https://drive.google.com/drive/folders/1LUiOWPHQUyaQIU-xASJTmVs8LoiMYfW4?usp=sharing

Thanks for the continued support and troubleshooting!

**Comment by rafalkowalewski1** [comment]
Hello,

Thank you for raising the issue and pointing out so much detail! You are right, most likely the errors occur due to the updated dependencies and it's difficult to predict what could go wrong here. I will take a look at this in the coming days.

Bests,
Rafal

**Comment by rafalkowalewski1** [comment]
Hi, I updated picasso to 0.6.5, using your method, everything should work fine now.

Bests,
Rafal

**Comment by GolgiWhillikers** [comment]
Confirmed for me that all the cmd functions worked appropriately in a fresh env using 0.6.5. Thanks for the quick update.
