### ISSUE TITLE
Issue with clustering functions output

### ISSUE THREAD

**Issue by lilbutsa** [jungmannlab/picasso#428]
* Picasso version: 0.6.7
* Python version: Stand alone windows install
* Operating System:Windows 10

### Description
I think I might have found a bug in the output of the clustering functions. When using the DBScan and SMLMClusterer clustering functions, the HDF5 output has two headings: area and convexhull. At the moment these two values are always identical to the net_gradient and n values respectively. I assume they meant to be the cluster area from the DBscan threshold and the convexhull area?

This is the case for both the general output file and the cluster centres file.

Thanks in advance for any help/clarification.

![Clustering_Output_Bug_Screenshot](https://github.com/jungmannlab/picasso/assets/45649772/118656bc-2eea-4b11-880d-afe231a7d758)

**Comment by rafalkowalewski1** [comment]
Hi,

Thanks a lot for pointing out this error. It will be solved in the next Picasso release (most probably next week).

Bests,
Rafal
