### ISSUE TITLE
Add support for tiff file names

### ISSUE THREAD

**Issue by ajasja** [jungmannlab/picasso#429]
Picasso is great! However, our instrument saves .tiff files instead of .tif.
If we just rename them from tiff -> tif everything works correctly. 

Would it be possible to change line
https://github.com/jungmannlab/picasso/blob/846e012cb59b79405098c8a502f96ec607d48aa1/picasso/io.py#L187
From    
`elif ext == ".tif":`
to 
`elif (ext == ".tif") or (ext == ".tiff"):`

We could also print a waring `Tiff files are not officially supported`. But for us everything has been working great, just by renaming.  

I'm happy to do a PR if you would be willing to entertain this idea. 

* Picasso version: 0.6.6
* Python version: 3.10
* Operating System: Windows

### Description

Trying to load a tiff file from a LUMICSK C-TRAP EDGE 350

**Comment by rafalkowalewski1** [comment]
Hi Ajasja,

I will add this line of code. The next release should be ready the next week.

Bests,
Rafal

**Comment by ajasja** [comment]
Thank you!
