### ISSUE TITLE
Example notebook missing table name to read pandas dataframe

### ISSUE THREAD

**Issue by ajasja** [jungmannlab/picasso#430]
* Picasso version: 0.67
* Python version: 3.10
* Operating System: Win11

### Description

I believe the example (https://github.com/jungmannlab/picasso/blob/master/samples/SampleNotebook.ipynb) code to read localisation to a pandas dataframe is missing the table name `'locs'`
### What I Did

Without table name:
![image](https://github.com/jungmannlab/picasso/assets/19926/ab04b453-b789-4377-9c55-e215184b0789)

With table name:
![image](https://github.com/jungmannlab/picasso/assets/19926/b4a94ceb-9e57-42ce-85e6-6f245ec84b63)

**Comment by rafalkowalewski1** [comment]
Hi Ajasja,

Thanks for the note, I will try to release the updated version today.

Bests,
Rafal
