### ISSUE TITLE
z-position wrongly saved in csv files?

### ISSUE THREAD

**Issue by MNFHensgens** [jungmannlab/picasso#436]
* Picasso version:0.6.7
* Python version: Windows install
* Operating System: Windows 10

### Description

Hi, I saved my rendered 3D image to a .csv file with the help of Picasso render. Now I notice that the z-position of all my localizations is multiplied by 160 nm (pixel size of x and y). So now I divide all the z-positions by 160 nm to get the right scaling in z. 

I think something is going wrong during the saving procedure to a different file type. When I open the same file in Picasso filter I get the correct z-positions.

**Comment by rafalkowalewski1** [comment]
Hi,

What you observed is the known feature of Picasso, please see here: https://picassosr.readthedocs.io/en/latest/files.html#localization-hdf5-files

Bests,
Rafal
