### ISSUE TITLE
Suggestion: Implement different AIM drift correction algorithm (or DME)

### ISSUE THREAD

**Issue by ajasja** [jungmannlab/picasso#450]
I recently came across this paper (https://www.science.org/doi/10.1126/sciadv.adm7765), which presents a novel drift correction method called AIM.
![image](https://github.com/jungmannlab/picasso/assets/19926/00e22ebd-5115-4c4d-8dc2-df742358979d).

It looks almost too good to be true. We are planning to test the Matlab version (https://github.com/YangLiuLab/AIM).
If it works well, would there be interest in including AIM in picasso? (I realize there is no Python version yet, but the algorithm seems quite easy to port over to Python). 

Any comments on AIM are also welcome.

**Comment by rafalkowalewski1** [comment]
Hi, 

I agree, the algorithm looks great, we will consider your suggestion!

Bests,
Rafal

**Comment by ajasja** [comment]
So it seems to work at least as good as RCC. Is there a good way to quantify resolution? I guess I could do a nearest neighbor analysis. 

RCC:
![image](https://github.com/jungmannlab/picasso/assets/19926/65b384a7-774d-49fb-8e2b-49071854ada2)

AIM:
![image](https://github.com/jungmannlab/picasso/assets/19926/476c5a7b-8404-4cf9-9c2d-27b7676af10e)


The algorithm was super fast. About 2 s. RCC was about 5-10s.

I wrote a hacky matlab script 
[AIM-main.zip](https://github.com/user-attachments/files/15621776/AIM-main.zip)
to do the alignment:
```matlab
%% Example code
   % align the picasso images
clc
clear
close all
warning('off')
addpath(genpath('.'))
addpath(genpath('./AIM'))
addpath(genpath('./DME_RCC'))
addpath(genpath('./Data'))

%% Load HDF5 picasso
in_file = 'Data/C1-20240604-164932_WT.ome_locs.hdf5'
%inh5 = H5F.create (in_file, 'H5F_ACC_TRUNC', 'H5P_DEFAULT', 'H5P_DEFAULT');

%% load HDF5
locs = h5read(in_file, '/locs') 

%% align

Localizations(:,1) = double(locs.frame);
Localizations(:,2) = double(locs.x);
Localizations(:,3) = double(locs.y);

%% AIM drift correction
trackInterval = 50; % time interval for drift tracking, Unit: frames 
t_start = tic;
[LocAIM, AIM_Drift] = AIM(Localizations, trackInterval);
AIM_time = toc(t_start)

%% save output
olocs.frame = LocAIM(:, 1) 
olocs.x = LocAIM(:, 2) 
olocs.y = LocAIM(:, 3) 
olocs.lpx = locs.lpx
olocs.lpy = locs.lpy


out_name = [in_file(1:end-4) '_undrifted.hdf5']

% Not working for some reason in 2020b
% h5write(out_name, '/locs', locs)
save_picasso('.', out_name, olocs)
```

**Comment by rafalkowalewski1** [comment]
AIM will be implemented in Picasso 0.7.0.

**Comment by ajasja** [comment]
Thanks! Looking forward to that.

**Comment by ajasja** [comment]
Amazing, I just saw AIM is now in 0.7. Can't wait to try it out.

**Comment by rafalkowalewski1** [comment]
The installer is in the making : )
