### ISSUE TITLE
localize via command-line + mle fitting: sx == sy

### ISSUE THREAD

**Issue by MariusGlg** [jungmannlab/picasso#482]
* Picasso version: 0.6.11
* Python version: 3.10.13
* Operating System: Windows

### Description

The Point Spread Function width in camera pixels is equal in x & y (sx == sy) when using the command line for localization + mle as the fitting option. This is not the case when using mle fitting in the picasso render module (see file attached)
![cmd localize](https://github.com/jungmannlab/picasso/assets/93711777/ebba5e62-ea2c-41e2-9f2b-528b73adab39)

### What I Did

```
picasso localize "filepath" -b 7 -a mle -g 150000 -r 165 122 267 227 -bl 200
```

**Comment by rafalkowalewski1** [comment]
Hello Marius,

Thank you for pointing this out. I will fix this at the new update.

Bests,
Rafal

**Comment by rafalkowalewski1** [comment]
Hello Marius,

I decided that the CMD version should output different sigmas for x and y (this can be useful for filtering spots that have too different values later). The update will be available next week.

Bests,
Rafal
