### ISSUE TITLE
Linking of localizations does not work in v0.7.0

### ISSUE THREAD

**Issue by CKSpahn** [jungmannlab/picasso#492]
* Picasso version: v0.7.0 (executable installation and python distribution)
* Python version: 3.10
* Operating System: Windows 11 Enterprise

### Description

Dear Picasso Team,

first of all thanks for the great software and the constant updates. 
When using the most recent version (v0.7.0), I experienced that linking of localization is not working properly. During linking (both executable installation and python distribution), I get the following error message:

![grafik](https://github.com/user-attachments/assets/38b747c5-70ac-4845-97ed-599da5a0119d)

Best wishes,
Chris

**Comment by alicia-cuber** [comment]
Hi, 
I am having the same problem (also in v0.7.0), I noticed that there has a been a new release and I was wondering if this has been resolved in the new version. If so, I will switch over. 
Best, 
Alicia

**Comment by rafalkowalewski1** [comment]
Hi, the issue was resolved in 0.7.3.

Bests,
Rafal
