### ISSUE TITLE
export as .csv for ThunderSTORM, The z (nm) column in the 3D data was incorrectly enlarged

### ISSUE THREAD

**Issue by 15927335750** [jungmannlab/picasso#494]
### Description

When export as .csv for ThunderSTORM
The z (nm) column in the 3D data was incorrectly enlarged, and z (nm) was already nm unit in the original.hdf5 file. When exported to.csv, the data was enlarged by multiplying pixelsize again

<img width="981" alt="0e73da624f6b0f1d936422639540317" src="https://github.com/user-attachments/assets/b41b5fdf-601c-4a42-96b0-be78803c02bd">

**Comment by rafalkowalewski1** [comment]
Thank you for pointing out the error, it will be fixed in the next release.

Bests,
Rafal
