### ISSUE TITLE
Picasso:Average clusters 

### ISSUE THREAD

**Issue by MiHoltma** [jungmannlab/picasso#78]
* Picasso version: 0.28
* Python version: 3.7.4
* Operating System: Windows 10 

### Description

Hi, 

We recently got our hands on the U2OS Nup96-mEGFP cells and are currently trying severaly things. 
Everything seems to run fine, but we got issues using Picasso:Average. No matter which parameters we try, the nuclear pore structure clusters in 1 to 3 spots after very few iterations (>1-2) (see attachment before and after averaging).

![grafik](https://user-images.githubusercontent.com/60345298/73186938-dcf4a180-4120-11ea-9dd4-1f41c7490393.png)
![grafik](https://user-images.githubusercontent.com/60345298/73186972-eda51780-4120-11ea-9df5-769b52121da6.png)

We also experience the error "failed to execute Picasso script", but that is not always the case.

**Comment by straussmaximilian** [comment]
Hi,

The clustering into a few spots is, unfortunately, a problem that arises from the fundamental algorithm that uses a cross-correlation approach. Bright pixels can dominate the image and the averaging process locks into these bright spots. This highly depends on the number of samples you choose and the labeling efficiency. 

Typically, an iterative approach, starting with low oversampling (1-2) and only a few iterations (1-2) and slowly increasing the oversampling can be beneficial.

if you have the Python Version installed I would suggest using the `average3`- module. Initially, it was written to be used for 3D datasets but can also be used for 2D. It is not optimized for speed but many more options are available, i.e. if you want to constrain on an 8-fold symmetry. To start type `python -m picasso average3` in your respective folder and environment.

This module was used to create the averages of NUPs as shown in this [paper](https://onlinelibrary.wiley.com/doi/full/10.1002/anie.201905685). Feel free to read about the oversampling settings in the SI.
I hope that helps.
