### ISSUE TITLE
Coefficients from 3D calibration

### ISSUE THREAD

**Issue by cleterrier** [jungmannlab/picasso#9]
What model is used for astigmatism fitting in Picasso? Are the coefficient corresponding to the defocusing curve from Huang et al. Science 2008, and if so in which order? This would be useful to compare 3D calibration from Picasso to the one from N-STORM (which is based on the Huang model).

<img width="274" alt="huang_defocus" src="https://user-images.githubusercontent.com/1062283/38163390-d2c374b0-34f3-11e8-90bd-1cf80ca9b478.png">

**Comment by straussmaximilian** [comment]
The model is an adaption of the Huang Paper but uses a six-degree polynomial for fitting.
I made an entry on the wiki to clarify this:
https://github.com/jungmannlab/picasso/wiki/Localize
